create login page
COMP1640-TCH2202/GIdea-React pull request #1
Opened 2023-02-22 15:21 UTC by ngochieudo

2023-02-22 16:00 UTC, AvoDieKatz requested changes
Đang có conflict trong file App.js, pull về resolve rồi push lại nhé

2023-02-22 18:09 UTC, AvoDieKatz requested changes
Vẫn conflict, phải xoá cả mấy cái mũi tên <,>,= chứ

2023-02-22 18:11 UTC, AvoDieKatz commented
Tải thử mấy cái extension như GitLens về thao tác cho dễ

2023-02-23 06:52 UTC, ngochieudo commented
t vừa sửa lại cả phần app.css với app,js rồi

2023-02-23 14:24 UTC, closed without merging

2023-02-23 14:25 UTC, AvoDieKatz commented
Không check được build, sẽ mở lại một PR khác